@startuml
class EnemyTurnHandler {
    - _battleStateMachine : BattleStateMachine
    - _abilityExecutor : AbilityExecutor
    + EnemyTurnHandler(battleStateMachine:BattleStateMachine, abilityExecutor:AbilityExecutor)
    + <<async>> StartEnemyTurn() : void
}
@enduml
