@startuml
enum StatType {
    Level,
    Experience,
    StarRating,
    Strength,
    Agility,
    Magik,
    AdherenceToCommand,
    Leadership,
    Health,
    Speed,
    Potency,
    Resilience,
    Bloodlust,
    CriticalDamage,
    DefenseNegation,
    PhysicalOffense,
    PhysicalCriticalChance,
    ArmorPierce,
    PhysicalAccuracy,
    Armor,
    PhysicalDodge,
    PhysicalCriticalAvoidance,
    MagikOffense,
    MagikCriticalChance,
    MagikArmorPierce,
    MagikAccuracy,
    MagikArmor,
    MagikDodge,
    MagikCriticalAvoidance,
}
@enduml
